host: localhost:8080
info:
  contact: {}
  description: Matching app
  title: Matching app
  version: "1.0"
paths:
  /api/v1/health-check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: health check
swagger: "2.0"
