definitions:
  error_handler.ErrorResponse:
    properties:
      error:
        type: string
      error_detail:
        items:
          type: string
        type: array
      status:
        type: integer
    type: object
  request.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  response.AuthenticationResponse:
    properties:
      api_token:
        description: IDトークン
        type: string
    required:
    - api_token
    type: object
  response.InitialResponse:
    properties:
      current_version:
        description: current version
        type: string
      min_version:
        description: min version
        type: string
    required:
    - current_version
    - min_version
    type: object
  response.LoginUserResponse:
    properties:
      authentication:
        $ref: '#/definitions/response.AuthenticationResponse'
      me:
        $ref: '#/definitions/response.MeResponse'
    required:
    - authentication
    - me
    type: object
  response.MeResponse:
    properties:
      email:
        description: メールアドレス
        type: string
      id:
        description: ID
        type: string
      name:
        description: 名前
        type: string
    required:
    - email
    - id
    - name
    type: object
host: localhost:8080
info:
  contact: {}
  description: Matching app
  title: Matching app
  version: "1.0"
paths:
  /api/v1/health-check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: health check
      tags:
      - health check
  /api/v1/initial:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.InitialResponse'
      summary: アプリ起動時にコールする
      tags:
      - initial
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: ログイン処理を行う。JWTを新たに発行する
      parameters:
      - description: ログイン情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error_handler.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/error_handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error_handler.ErrorResponse'
      summary: ログイン
      tags:
      - auth
  /api/v1/users:
    post:
      consumes:
      - application/json
      description: 新しいユーザーを作成する
      parameters:
      - description: ユーザー情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.LoginUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error_handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error_handler.ErrorResponse'
      summary: ユーザー新規作成
      tags:
      - users
  /api/v1/users/me:
    get:
      consumes:
      - application/json
      description: ログイン中のユーザー情報を取得する
      parameters:
      - description: ログイン時に取得したIDトークン(Bearer)
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.MeResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/error_handler.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/error_handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error_handler.ErrorResponse'
      summary: ログインユーザー情報取得
      tags:
      - users
swagger: "2.0"
